twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        visitor_helper: '@App\Service\VisitorHelper'
        article_file_directory: '%article_file_directory%'

    form_themes: ['bootstrap_4_layout.html.twig']